name: check reviewers workflow.
on:
  pull_request:

jobs:
  check-reviewers:
    runs-on: ubuntu-latest 
    steps:
      - name: check reviewers on pull request review trigger
        uses: actions/checkout@v3
        with:
          repository: DerekFangming/actiontest
          path: /
